export const state = {
	userDetails: "",
	loggedIn: false,
	firstName: "Not logged In",
	profileDetails:"",
	availableJobs:[
      { text: 'WHEELSEYE', img: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAMAAQDGAAoAAQAAAAAAAAuaAAAAJDhlZmY5ZDQyLTcwNDItNDdkNC05OTVkLWFhNjlmNTRmYjkwMA.png', desc:"UI Developer", exp:"2-4 years", location:"Gurgaon"},
      { text: 'WHEELSEYE', img: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAMAAQDGAAoAAQAAAAAAAAuaAAAAJDhlZmY5ZDQyLTcwNDItNDdkNC05OTVkLWFhNjlmNTRmYjkwMA.png', desc:"UX Developer", exp:"2-4 years",  location:"Gurgaon"},
      { text: 'WHEELSEYE', img: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAMAAQDGAAoAAQAAAAAAAAuaAAAAJDhlZmY5ZDQyLTcwNDItNDdkNC05OTVkLWFhNjlmNTRmYjkwMA.png', desc:"Backend Developer", exp:"0-2 years",  location:"Gurgaon" }
    ],
    slicers:[{job:'UI/UX', city: "Bangalore"}, {job:"Graphic, Art direction", city:"Hyderabad"}, {job:"Automotive and industrial", city:"Mumbai"}, {job:"Web and Mobile deveopment", city:"Delhi"}, {job:"Animation, motion and Post production", city:"Chennai"}, {job:"Fashion", city:"Noida"}],
	apiResult: false,
	jds:[{aboutRole:["Backend Engineers at Wheelseye are a small group of people who directly impact the daily lives of 100s of truckers nationally. As a backend engineer, you are the architect, designer and coder of your project. In addition, you work closely with the product team to make vision become reality. You are dynamic and able to work well both independently and as part of a team.", 

"Backend engineers at Wheelseye are building the next-generation technologies that change the way how logistics industry connect, explore, and interact with information and one another. Our software absorbs, handles & processes data at massive scale. We're looking for ace humans and experienced engineers who bring fresh ideas from all areas, including information retrieval, distributed computing, large-scale system design, networking and data storage, security, artificial intelligence, natural language processing, UI design and mobile; the list goes on and is growing every day. We need our engineers to be versatile, display leadership qualities and be enthusiastic to take on new problems across the full-stack as we continue to push technology forward.",

"At Wheelseye, we leave all egos at the door and concentrate on the job at hand. We value passionate, down to earth, “can do” people who enjoy fine-tuning small details, without losing sight of the big picture. We are looking for the type of person who feels uncomfortable when a day goes by without achieving something impactful." ,

"Someone who is driven to get things done and views obstacles as an exciting challenge that demands a creative solution. Above all else, this role requires someone who takes great pride in their work and is inspired and motivated by their role in improving the way millions of people drive worldwide."], resposibilities: ["Design, develop, test, deploy, maintain and improve software.", "Manage individual project priorities, deadlines and deliverables.", "Server side of our web applications."], eligibility:["Excellent programming skills and a passion for developing applications or improving existing ones", "Pursuing B Tech/ BE degree in Computer Science, a related technical field of study, or relevant practical industry experience", "Maximum 2 Years of Experience", "Strong OOPS concepts", "Algorithms, DS, Problem Solving & Analytical Approach in Solutions", "Experience with JAVA, Spring and other concepts of programming in JAVA", "Strong object-oriented, database design and SQL skills", "Interest and ability to learn other coding languages as needed"], 
remuneration: ["INR 6,00,000 - INR 14,00,000 Annual ", "Upto .1% ESOPS"], about:["Wheelseye offers technology to empower truckers. Our software helps save costs, build safe and secure infrastructure, automate operations and streamline your business. We provide end to end technology backend from basic things like GPS live location tracking to complex tasks like driving profitability and automation in your business.", "Our Software as a Service enables data driven decision making by reading a number of connected devices. We give highest priority to security and safety of your infrastructure & data. Our platform is fully customizable and can be tailored as per the needs of your business and targets. ", "We are a young and energetic team of IIT graduates having rich industry and technology experience. Our mission to become the preferred technology partner to our business partners. It is our constant endeavour to constantly create and evolve data-driven software solutions that conquer business problems and inspire smarter decisions."] 
}]
}
